name = "pokewatch-cron"
main = "worker.js"
compatibility_date = "2026-08-01"
keep_vars = true

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "STATE"
id = "6328c9cf64f9486cafd78491f3c294b1"

# Secret à définir dans le dashboard : DISCORD_WEBHOOK_URL
